package com.lctapp.lct.Classes

import java.io.Serializable

class MemberData : Serializable{

        var memberId = 0
        var customerId = 0
        var merchantId: String? = null
        var memberNo: String? = null
        var firstName: String? = null
        var lastName: String? = null
        var fullName: String? = null
        var deviceId: String? = null
        var respCode = 0
        var bioId: String? = null
        var fileName: String? = null
        var createdBy = 0
        var memberIdList: String? = null
        var isSelected = false
        var isExpanded = false
        var memberType: String? = null
        var lctCode: String? = null
        var title: String? = null
        var otherName: String? = null
        var idPassPortNo: String? = null
        var gender: String? = null
        var maritalStatus: String? = null
        var weight: String? = null
        var height: String? = null
        var nhifNo: String? = null
        var employerName: String? = null
        var occupation: String? = null
        var nationality: String? = null
        var postalAdd: String? = null
        var physicalAdd: String? = null
        var homeTelephone: String? = null
        var officeTelephone: String? = null
        var cellPhone: String? = null
        var email: String? = null
        var cardStatus: String? = null
        var uploadStatus: String? = null
        var accType = 0
        var cardNumber: String? = null
        var serialNumber: String? = null
        var expiryDate: String? = null
        var status: String? = null
        var binRange: String? = null
        var programmeId = 0
        var programmeDesc: String? = null
        var imageList: String? = null
        var bioImages: String? = null
        var biometrics: String? = null
        var bioImage: String? = null
        var cardBalance = 0
        var cardSerialNo: String? = null
        var cardPin: String? = null
        var familySize = 0
        var bnfGrpId = 0
        var bnfStatus: String? = null
        var verifyStatus: String? = null
        var approveStatus: String? = null
        var bioStatus: String? = null
        var isPrintStatus = false
        var isRightPrint = false
        var isLeftPrint = false
        var memType: String? = null
        var familyMemList: List<FamilyMembers>? = null
        var isChecked = false
        var serialNo: String? = null
        var verifySelection: String? = null
        var famVerifySelection: String? = null
        var userName: String? = null
        var userEmail: String? = null
        var topupCount = 0
        var bnfGrpName: String? = null
        var productId = 0
        var isActive = false
        var accNo = 0
        var accNumber: String? = null
        var accId = 0
        var accBalance = 0
        var orgId = 0
        var memberProgrammes: String? = null
        var fromDate: String? = null
        var toDate: String? = null
        var count = 0
        var nationalId: String? = null
        var scheme: String? = null
        var isSchemeActive = false
        var isSchemeExpired = false
        var isHasSpouse = false
        var relation: String? = null
        var principleId = 0
        var principle: String? = null
        var voucherId = 0
        var age = 0
        var familyMemId = 0
        var famMemberNo: String? = null
        var famMemFirstName: String? = null
        var famMemLastName: String? = null
        var famMemFullName: String? = null
        var famDob: String? = null
        var famGender: String? = null
        var famMemNationalId: String? = null
        var relationId = 0
        var relationDesc: String? = null
        var familyMemPic: String? = null
        var familyMemBioId = 0
        var tempFamilyMemId = 0
        var isEditMode = false
        var iconStyle: String? = null
        var isCancelled = false
        var famPic: String? = null
        var isNew = false
        var idNumber = 0
        var productName: String? = null
        var orgName: String? = null
        var famMemPhoneNumber: String? = null
        var verificationType: String? = null
        var payer: String? = null
        var copay = 0
        var disabled: String? = null
        var buffer = 0
        var deviceID: String? = null
        var sessionName: String? = null
        var hospitalName: String? = null
        var expireTime: String? = null
        var activationTime: String? = null
        var schemeId = 0
        var salutation: String? = null
        var familyCode: String? = null
        var policyId = 0
        var expiryTime: String? = null
        var search_results: String? = null
        var memberPic: String? = null
        var other_name: String? = null
        var first_name: String? = null
        var id_number: String? = null
        var date_of_birth: String? = null
        var citizenship: String? = null
        var insuranceCode: String? = null
        var schemeCode: String? = null
        var outpatientStatus: String? = null
        var surname: String? = null
}
