package com.lctapp.lct.Classes.Models.MemberBalances

import com.lctapp.lct.Classes.Models.MemberBalances.MemberProgramme

import com.fasterxml.jackson.annotation.JsonProperty
import java.io.Serializable

class MemberBalances:Serializable {
    var memberId = 0
    var customerId = 0
    var merchantId: Any? = null
    var memberNo: String? = null
    var firstName: Any? = null
    var lastName: Any? = null
    var fullName: String? = null
    var dateOfBirth: String? = null
    var deviceId: Any? = null
    var respCode = 0
    var bioId: Any? = null

    @JsonProperty("FileName")
    var fileName: Any? = null
    var createdBy = 0
    var memberIdList: Any? = null
    var vouchers: Any? = null
    var memberServices: Any? = null
    var selected = false
    var expanded = false
    var memberType: Any? = null
    var lctCode: Any? = null
    var title: Any? = null
    var otherName: Any? = null
    var idPassPortNo: Any? = null
    var gender: String? = null
    var maritalStatus: Any? = null
    var weight: Any? = null
    var height: Any? = null
    var nhifNo: Any? = null
    var employerName: Any? = null
    var occupation: Any? = null
    var nationality: Any? = null
    var postalAdd: Any? = null
    var physicalAdd: Any? = null
    var homeTelephone: Any? = null
    var officeTelephone: Any? = null
    var cellPhone: Any? = null
    var email: Any? = null
    var cardStatus: Any? = null
    var uploadStatus: Any? = null
    var accType = 0
    var cardNumber: Any? = null
    var serialNumber: Any? = null
    var expiryDate: Any? = null
    var status: Any? = null
    var programmes: Any? = null
    var binRange: Any? = null
    var programmeId = 0
    var programmeDesc: String? = null
    var imageList: Any? = null
    var bioImages: Any? = null
    var biometrics: Any? = null
    var bioImage: Any? = null
    var cardBalance = 0.0
    var cardSerialNo: Any? = null
    var cardPin: Any? = null
    var familySize = 0
    var bnfGrpId = 0
    var bnfStatus: Any? = null
    var verifyStatus: Any? = null
    var approveStatus: Any? = null
    var bioStatus: Any? = null
    var printStatus = false
    var rightPrint = false
    var leftPrint = false
    var memType: String? = null
    var familyMemList: Any? = null
    var isChecked = false
    var serialNo: Any? = null
    var verifySelection: Any? = null
    var famVerifySelection: Any? = null
    var userName: Any? = null
    var userEmail: Any? = null
    var topupCount = 0
    var bnfGrpName: Any? = null
    var productId = 0
    var active = false
    var accNo = 0
    var accNumber: Any? = null
    var accId = 0
    var accBalance = 0.0
    var orgId = 0
    var memberProgrammes: List<MemberProgramme>? = null
    var fromDate: Any? = null
    var toDate: Any? = null
    var count = 0
    var nationalId: Any? = null
    var scheme: String? = null
    var schemeActive = false
    var schemeExpired = false
    var hasSpouse = false
    var relation: Any? = null
    var principleId = 0
    var principle: Any? = null
    var voucherId = 0
    var age = 0
    var familyMemId = 0
    var famMemberNo: Any? = null
    var famMemFirstName: Any? = null
    var famMemLastName: Any? = null
    var famMemFullName: Any? = null
    var famDob: Any? = null
    var famGender: Any? = null
    var famMemNationalId: Any? = null
    var relationId = 0
    var relationDesc: Any? = null
    var familyMemPic: Any? = null
    var familyMemBioId = 0
    var tempFamilyMemId = 0
    var editMode = false
    var iconStyle: Any? = null
    var cancelled = false
    var famPic: Any? = null
    var isNew = false
    var idNumber = 0
    var productName: Any? = null
    var orgName: Any? = null
    var famMemPhoneNumber: Any? = null
    var verificationType: Any? = null
    var payer: Any? = null
    var copay = 0.0
    var disabled: Any? = null
    var buffer = 0.0
    var deviceID: Any? = null
    var sessionName: Any? = null
    var hospitalName: Any? = null
    var expireTime: Any? = null
    var activationTime: Any? = null
    var policyStartDate: Any? = null
    var policyEndDate: Any? = null
    var schemeId = 0
    var salutation: Any? = null
    var familyCode: String? = null
    var policyId = 0
    var expiryTime: Any? = null
    var search_results: Any? = null
    var guardian: Any? = null
    var memberPic: Any? = null
    var other_name: Any? = null
    var first_name: Any? = null
    var id_number: Any? = null
    var date_of_birth: Any? = null
    var citizenship: Any? = null
    var insuranceCode: Any? = null
    var schemeCode: Any? = null
    var outpatientStatus: String? = null
    var surname: Any? = null
}